### ISSUE TITLE
Testing rules

### ISSUE THREAD

**Issue by dolby360** [allero-io/allero#53]
Right now when adding [rules](https://github.com/allero-io/allero/tree/main/pkg/rulesConfig), the only way to test if it works is to actually run a build of allero PR branch on a real example.
There should be an easy way to test this, and this test shall be part of the github actions as well.
My initial thought was to have an examples folder of various github requests and another folder of tests.
```
├───allero
|   ├───pkg
|   |   └───rulesConfig
|   |   |   └───defaultRules
|   |   |       └───github
|   |   |   └───rulesConfig.go
|   |   |   └───tests
|   |   |   └───templates
```

**Comment by dimabru** [comment]
hey @dolby360,
I think we can use this issue to create our testing infra. 

I suggest looking at this example: https://github.com/datreeio/datree/tree/main/pkg/policy/tests
note that every rule has at least one pass and one fail example. there's a testing infra that reads that folder automatically and runs every rule against that specific object while expecting to pass/fail (according the test deifinition)

The logic that reads the rules themselves from the folder can be found here: https://github.com/datreeio/datree/blob/main/pkg/policy/policy_test.go

Make sure we also need to add a test step in the github workflows (on pr and the release workflow)

**Comment by dolby360** [comment]
Sure, thanks.

**Comment by dolby360** [comment]
Work is still in progress :), almost there.
