### ISSUE TITLE
Broken README link

### ISSUE THREAD

**Issue by Tamir198** [allero-io/allero#71]
Hey, this "here" link:

![image](https://user-images.githubusercontent.com/34707669/191782434-01a164ef-e291-4baf-9c47-d68b9a0cd9e8.png)
---
Is broken and leads to a 404 page:

![image](https://user-images.githubusercontent.com/34707669/191782502-a72f7af1-4c0f-4432-9930-16edd7ad672f.png)

**Comment by dolby360** [comment]
ngl it took me a while to understand this is a print screen. The link is working for me, can you check again?

**Comment by Tamir198** [comment]
@dolby360  Everything works now. I will close the issue thank you
