### ISSUE TITLE
Support fetch with full url

### ISSUE THREAD

**Issue by dimabru** [allero-io/allero#93]
**Describe the solution you'd like**
We need to be able to support fetching with full url (instead of just owner/repo)
For example: 
`allero fetch https://github.com/allero-io/allero`
`allero fetch https://github.com/allero-io`

**Comment by jmj0502** [comment]
Hey! I would like to help with this issue. Can you please, provide a little more detail in regard to which changes should be made to the code?

**Comment by dimabru** [comment]
hey @jmj0502 
Thanks a lot for offering to take this issue!
I've already started working on it but may I suggest you take #78?

Also, once I'm done with this issue you can take #94 if you'd like :)
